### ISSUE TITLE
Getting Wrong Results 

### ISSUE THREAD

**Issue by game-sys** [foamliu/Car-Recognition#11]
I am getting this result on the image of Lamborghini Reventon Coupe 2008 in the Sample folder
I have downloaded model from **https://drive.google.com/file/d/0Byy2AcGyEVxfeXExMzNNOHpEODg/view**  link saved it in models/resnet152_weights_tf.h5 in the repository I have changed weights in demo.py and utils.py  from models/model.96-0.89.hdf5 to models/resnet152_weights_tf.h5 and i am getting this result,
Secondly, I am also getting different result every time on same image 
Please help to replicate your claim,
[{'label': 'Acura ZDX Hatchback 2012', 'prob': '0.101'}]

**Comment by foamliu** [comment]
Please refer to https://github.com/foamliu/Car-Recognition/issues/12.
