### ISSUE TITLE
License Information

### ISSUE THREAD

**Issue by BaruchG** [foamliu/Car-Recognition#14]
I have been enjoying your license plate detector and have been learning a lot from it but I noticed there was no licensing information included for usage purposes. I’m wondering two things:
1.	Could you tell me what this is licensed under for usage or what the rights to use are?
2.	If it does have a license that was mistakenly not added the repo, any chance you could please put it up?

You can find out more about different available licenses through Github at https://help.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository .  If you would like use a minimally restrictive license without any liability on your part, the MIT license, available at https://choosealicense.com/licenses/mit/ , is a good option.
Thanks so much for your work!

**Comment by foamliu** [comment]
Thanks for reminder, added.
