### ISSUE TITLE
Question while training

### ISSUE THREAD

**Issue by jy016011** [foamliu/Car-Recognition#5]
Hello foamliu,

Thanks for your efforts first.

While I was training, I realized that each epoch takes too much time. (*ETA: 273 average.)

Is this normal?, or do I something wrong?

Thanks. 

(My envs: Python 3.6.7, tensorflow-gpu: 1.12.0rc2,Keras:2.2.4, using anaconda env)

**Comment by jy016011** [comment]
sorry my mistake.

i dealt with it

**Comment by foamliu** [comment]
Hello @jy016011 , how did you fixed the performance issue please?
