### ISSUE TITLE
Deploy the test

### ISSUE THREAD

**Issue by GuillaumeUnice** [foamliu/Car-Recognition#7]
Hi your work is fascinating!

I'm a noob in Python, and I've just intalled Pythond 3.X and try to use the test.py.
So first of first try to install the requirements and bump to the follwing error regarding tensorflow-gpu
```
Collecting tensorflow-gpu
  ERROR: Could not find a version that satisfies the requirement tensorflow-gpu (from versions: none)
ERROR: No matching distribution found for tensorflow-gpu`
```

I've owned an Intel Graphics 520 on Windows OS, is that problematic?

Thanks in advance

**Comment by foamliu** [comment]
This seems a problem of tensorflow installation.
